begin;

-- ============================================================
-- Object dossier ingestion bookkeeping (ADR 012)
--
-- Real data enters through a transactional importer, not through
-- seed.sql or migrations. These tables record which packets were
-- imported and bind packet-local symbolic keys to canonical rows.
-- Canonical UUIDs are always generated by PostgreSQL; bindings are
-- the only repeatability mechanism.
-- ============================================================

create schema if not exists ingestion;

create table ingestion.dataset (
    id uuid primary key default gen_random_uuid(),
    -- Stable logical identifier for a packet lineage,
    -- for example: mosa-bootstrap.
    key text not null unique
        check (length(btrim(key)) > 0),
    title text
        check (title is null or length(btrim(title)) > 0),
    created_at timestamptz not null default now()
);

create table ingestion.run (
    id uuid primary key default gen_random_uuid(),
    dataset_id uuid not null
        references ingestion.dataset(id)
        on delete cascade,
    packet_version text not null
        check (length(btrim(packet_version)) > 0),
    -- Hex SHA-256 of the canonicalised packet JSON.
    packet_sha256 text not null
        check (packet_sha256 ~ '^[0-9a-f]{64}$'),
    importer_version text not null
        check (length(btrim(importer_version)) > 0),
    status text not null default 'running'
        check (status in ('running', 'succeeded', 'failed')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    error text,
    constraint run_finished_when_terminal
        check (
            (status = 'running') = (finished_at is null)
        ),
    constraint run_error_only_when_failed
        check (
            error is null
            or status = 'failed'
        )
);

-- A packet checksum that already succeeded for a dataset makes an
-- identical reimport a detectable no-op.
create unique index run_succeeded_packet_idx
    on ingestion.run (dataset_id, packet_sha256)
    where status = 'succeeded';

create index run_dataset_idx
    on ingestion.run (dataset_id);

create table ingestion.entity_binding (
    dataset_id uuid not null
        references ingestion.dataset(id)
        on delete cascade,
    -- Packet-local symbolic key, for example: item:hoa-hakananai-a.
    local_key text not null
        check (length(btrim(local_key)) > 0),
    entity_id uuid not null
        references entities.entity(id)
        on delete cascade,
    created_at timestamptz not null default now(),
    primary key (dataset_id, local_key)
);

create index entity_binding_entity_idx
    on ingestion.entity_binding (entity_id);

create table ingestion.claim_binding (
    dataset_id uuid not null
        references ingestion.dataset(id)
        on delete cascade,
    local_key text not null
        check (length(btrim(local_key)) > 0),
    claim_id uuid not null
        references knowledge.claim(id)
        on delete cascade,
    created_at timestamptz not null default now(),
    primary key (dataset_id, local_key)
);

create index claim_binding_claim_idx
    on ingestion.claim_binding (claim_id);

create table ingestion.evidence_binding (
    dataset_id uuid not null
        references ingestion.dataset(id)
        on delete cascade,
    local_key text not null
        check (length(btrim(local_key)) > 0),
    claim_evidence_id uuid not null
        references knowledge.claim_evidence(id)
        on delete cascade,
    created_at timestamptz not null default now(),
    primary key (dataset_id, local_key)
);

create index evidence_binding_evidence_idx
    on ingestion.evidence_binding (claim_evidence_id);

comment on schema ingestion is
    'Bookkeeping for the object dossier importer: datasets, import runs and bindings from packet-local keys to canonical rows. See ADR 012.';
comment on table ingestion.dataset is
    'A logical source packet lineage identified across repeated imports.';
comment on table ingestion.run is
    'One attempted import of a packet. A succeeded (dataset_id, packet_sha256) pair is unique so identical reimports are no-ops.';
comment on table ingestion.entity_binding is
    'Binds a packet-local entity key to its canonical entity. Canonical UUIDs are never derived from local keys.';
comment on table ingestion.claim_binding is
    'Binds a packet-local claim key to its canonical claim.';
comment on table ingestion.evidence_binding is
    'Binds a packet-local evidence key to its canonical claim evidence row.';

-- ============================================================
-- Permissions
-- ============================================================

revoke all on schema ingestion from anon;
grant usage on schema ingestion to authenticated, service_role;

grant select, insert, update, delete
on all tables in schema ingestion
to authenticated, service_role;

alter default privileges for role postgres
in schema ingestion
grant select, insert, update, delete
on tables to authenticated, service_role;

-- ============================================================
-- Row-level security
-- ============================================================

alter table ingestion.dataset enable row level security;
alter table ingestion.run enable row level security;
alter table ingestion.entity_binding enable row level security;
alter table ingestion.claim_binding enable row level security;
alter table ingestion.evidence_binding enable row level security;

create policy "authenticated project access"
on ingestion.dataset
for all
to authenticated
using (true)
with check (true);

create policy "authenticated project access"
on ingestion.run
for all
to authenticated
using (true)
with check (true);

create policy "authenticated project access"
on ingestion.entity_binding
for all
to authenticated
using (true)
with check (true);

create policy "authenticated project access"
on ingestion.claim_binding
for all
to authenticated
using (true)
with check (true);

create policy "authenticated project access"
on ingestion.evidence_binding
for all
to authenticated
using (true)
with check (true);

commit;
